### ISSUE TITLE
Issue about contact

### ISSUE THREAD

**Issue by ghost** [IngoZenz/personalhttpproxy#2]
Hello @IngoZenz sorry to bug you here but the form on your website does not work
https://www.zenz-solutions.de/contact/

![Screenshot from 2024-05-08 23:05:31](https://github.com/IngoZenz/personalhttpproxy/assets/136118735/d9064973-81a2-4e8d-acc8-7c81bbf8da11)

And I found this the only way to contact you..

**Comment by IngoZenz** [comment]
Thanks for letting me know! Should be fixed now...

**Comment by ghost** [comment]
Hi @IngoZenz The website broke again. Would you be able to recommend anyone that can help me with my issue please?

**Comment by IngoZenz** [comment]
The contact form is working for me currently. But might be from time to time it fails. Need some time to look into it...
